# Site settings
title: Mixlr technology blog
email: jobs@mixlr.com
description: > # this means to ignore newlines until "baseurl:"
  Mixlr is an audio broadcasting company based in London. We'll be sharing some of what we learn about technology, coding and scalability on this blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tech.mixlr.com" # the base hostname & protocol for your site
twitter_username: mixlr
github_username:  mixlr

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
