# Site settings
title: Mixlr Tech
email: tech@mixlr.com
description: > # this means to ignore newlines until "baseurl:"
  Mixlr is an audio broadcasting company based in London. On Mixlr Tech, we'll be sharing some of what we learn about technology, coding and scalability.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tech.mixlr.com" # the base hostname & protocol for your site
twitter_username: mixlrtech
github_username:  mixlr

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
exclude:
  - Dockerfile
